# Hopfield networks

This notebook explains Hopfield networks as explored in Chapter Two of the book Machine Learning with Quantum Computers by Schuld and Petruccione.  

Hopfield networks have binary units $x_i \in \{-1,1\}$ for $j = 1, 2, \dots, N$ where $N$ is the number of nodes.  There are symmetric connections with $w_{ij} = w_{ji}$ and $w_{jj} = 0$.  We write the matrix $\boldsymbol{W}$ to represent the individual $w_{ij}$

Given a training point $\boldsymbol{x}^m = (x_1^m, x_2^m, \dots, x_N^m)$ it is argued that chosing the weights $w_{ij} \propto \sum_m x_i^m x_j^m$ leads to the $\boldsymbol{x}^m$ being stable states, or attractors of the network.  This means that an update of these states acts as the identity $\boldsymbol{\phi(Wx^m)} = \boldsymbol{x}^m$.  It is also argued that an Ising-type energy function:

$$
E_{\boldsymbol{w}}(\boldsymbol{x}) \;=\; -\frac{1}{2}\,\boldsymbol{x}^{\top}\mathbf{W}\,\boldsymbol{x}.
$$

decreases until it reaches one of the stable states, with an update rule:

$$
\boldsymbol{x}^{(t+1)} = \boldsymbol{\phi(Wx^{(t)})}
$$

Where the activation function $\phi$ is the standard percepton activation function.

$$
\phi(a) =
\begin{cases}
1, & a > 0, \\
-1, & \text{otherwise}.
\end{cases}
$$

Import the necessary functions.

In [1]:
import numpy as np
from pathlib import Path

HOME_DIR = '..'
BASE_DIR = Path(HOME_DIR)

import sys
sys.path.append(HOME_DIR)

from src.modules.calculation_helper_functions import (generate_random_x_vector,
                                                      generate_weight_matrix,
                                                      populate_weight_matrix,
                                                      calculate_energy,
                                                      calculate_update,
                                                      update_asynchronous,
                                                      overlap,
                                                      )

Main code:

In [2]:
#define constants and set initial seed
N = 30                  # Number of neurons
M = 3                   # Number of patterns to store
ITERATIONS = 3          # Number of iterations to run
SYNCHRONOUS = False     # Whether to use synchronous updates or not
PRINT_MATRICES = False  # Whether to print weight matrices or not
np.random.seed(42)

#generate random patterns and weight matrix
x = generate_random_x_vector(N, M) # patterns to store
W = generate_weight_matrix(N)      # weight matrix based on M patterns
print("Original patterns = \n", x)
W = populate_weight_matrix(W, x)
if PRINT_MATRICES:
    print("Populated Weight Matrix = \n", W)

for m in range(M): #calculate initial energies
    E = calculate_energy(W, x[:,m])
    print(f'Energy for pattern {m} = {E:.2f} initally')

x_new = generate_random_x_vector(N, 1) #generate new random vector
E = calculate_energy(W, x_new)         #calculate its energy
print(f'Energy for new random vector = {E:.2f} initally')

for t in range(ITERATIONS): #apply updates
    if SYNCHRONOUS:
        x_new = calculate_update(W, x_new)
    else:   
        x_new = update_asynchronous(W, x_new)
    print(f"Updated x at iteration {t} = \n", x_new)
    E = calculate_energy(W, x_new)
    print(f'Energy for updated new vector = {E:.2f} at iteration {t}')
    print(f'Calculating overlaps at iteration {t}.') 
    print('An overlap of 1.0 is perfect recall.')
    print('An overlap of -1.0 means perfect anti-correlation.')
    print('An overlap of 0.0 means no correlation.')
    for m in range(M):
        ov = overlap(x[:,m], x_new)
        print(f'Overlap with pattern {m} = {ov}.')


Original patterns = 
 [[-1  1 -1]
 [-1 -1  1]
 [-1 -1 -1]
 [ 1 -1 -1]
 [-1 -1  1]
 [-1  1  1]
 [ 1 -1  1]
 [-1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [-1 -1  1]
 [ 1  1 -1]
 [ 1 -1 -1]
 [-1 -1 -1]
 [ 1  1  1]
 [ 1  1 -1]
 [ 1  1 -1]
 [ 1 -1  1]
 [-1  1  1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1  1]
 [ 1 -1  1]
 [ 1  1  1]
 [-1  1 -1]
 [ 1  1  1]
 [-1  1 -1]
 [ 1 -1  1]
 [-1 -1  1]
 [-1  1  1]]
Energy for pattern 0 = -13.83 initally
Energy for pattern 1 = -13.77 initally
Energy for pattern 2 = -13.57 initally
Energy for new random vector = 0.10 initally
Updated x at iteration 0 = 
 [[-1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [-1]
 [-1]
 [-1]
 [-1]
 [ 1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [-1]]
Energy for updated new vector = -13.83 at iteration 0
Calculating overlaps at iteration 0.
An overlap of 1.0 is perfect recall.
An overlap of -1.0 means perfect anti-correlation.
An overlap of 0.0 means no correlation.
Overlap with pattern 0 = 1